# Generated by Django 4.2.2 on 2023-08-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('comestibles', 'Comestibles'), ('deportes', 'Deportes'), ('cuidado_personal', 'Cuidado Personal'), ('tecnología', 'Tecnología'), ('otro', 'Otro')], default='Comestibles', max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
