# Generated by Django 4.2.2 on 2023-08-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
