# Generated by Django 4.2.2 on 2023-08-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandsapp', '0002_delete_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='pics',
        ),
        migrations.AddField(
            model_name='marca',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='categoria',
            field=models.CharField(choices=[('comestibles', 'Comestibles'), ('deportes', 'Deportes'), ('cuidado_personal', 'Cuidado Personal'), ('tecnología', 'Tecnología'), ('autos', 'Autos'), ('otro', 'Otro')], default='Comestibles', max_length=30),
        ),
    ]
