# Generated by Django 4.2.2 on 2023-08-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandsapp', '0003_remove_marca_pics_marca_imagenes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='categoria',
            field=models.CharField(choices=[('food', 'Food'), ('deportes', 'Deportes'), ('cuidado_personal', 'Cuidado Personal'), ('tecnología', 'Tecnología'), ('autos', 'Autos'), ('otro', 'Otro')], default='Food', max_length=30),
        ),
    ]
